// Mobile Data-----------------------------------------------------------------

const productList = [
    {
        id:1,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/u/n/p/-original-imagugptgsfbxauz.jpeg?q=70',
        imgCousins:[
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/p/u/8/-original-imagugptptuacajg.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/t/c/p/-original-imagugptdmkvpwpm.jpeg?q=70',
            'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/f/r/2/-original-imagugptvr3dbzpb.jpeg?q=70'
        ],
        modelo:'vivo Y200 ',
        marca:'Vivo',
        precio:3000,
        color:'',
        espacio:'8 GB RAM | 128 GB ROM',
        camara:'64MP + 2MP | 16MP Camara Frontal',
        bateria:'4800 mAh bateria',
        cantidad:1,
        estaAgreado:false,
        tipo:'Mobile',   
        esTendencia:true,
        descripcion:"1 año de garantía del fabricante para el teléfono y 6 meses de garantía en la caja"
    },
    {
        id:2,
        img:"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/k/g/j/t3x-5g-v2338-vivo-original-imahyyzaqhgwzfup.jpeg?q=70",
        modelo:'Vivo T3x 5G',
        marca:'Vivo',
        precio:1500,
        espacio:'12 GB RAM | 256 GB ROM',
        camara:'108MP + 13MP + 2MP | 50MP Camara Frontal',
        bateria:'5000 mAh bateria',
        cantidad:1,
        estaAgreado:false,
        tipo:'Mobile',   
        esTendencia:false,
        descripcion:"1 año de garantía del fabricante para el teléfono y 6 meses de garantía en la caja"

    },
    {
        id:3,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/t/s/y/narzo-60-5g-rmx3750-realme-original-imagrht2yzyc2jyj.jpeg?q=70',
        modelo:'realme Narzo 60 ',
        marca:'Realme',
        precio:2500,
        espacio:'8 GB RAM | 128 GB ROM',
        camara:'64MP Camara Trasera',
        bateria:'5000 mAh bateria',
        cantidad:1,
        estaAgreado:false,
        tipo:'Mobile',   
        esTendencia:true,
        descripcion:"1 año de garantía del fabricante para el teléfono y 6 meses de garantía en la caja"
    },
    {
        id:4,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/2/z/4/-original-imagqxx2haehpjnf.jpeg?q=70',
        modelo:'realme 11 Pro ',
        marca:'Realme',
        precio:2300,
        espacio:'8 GB RAM | 128 GB ROM',
        camara:'100MP (OIS) + 2MP | 16MP Front camara',
        bateria:'5000 mAh bateria',
        cantidad:1,
        estaAgreado:false,
        tipo:'Mobile',   
        esTendencia:false,
        descripcion:"1 año de garantía del fabricante para el teléfono y 6 meses de garantía en la caja"
    },
    {
        id:5,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/h/h/d/-original-imags487gaqqhcea.jpeg?q=70',
        modelo:'realme C53',
        marca:'Realme',
        precio:1800,
        espacio:'6 GB RAM | 64 GB ROM',
        camara:'108MP + 2MP | 8MP Camara frontal',
        bateria:'5000 mAh bateria',
        cantidad:1,
        estaAgreado:false,
        tipo:'Mobile',   
        esTendencia:true,
        camara:'108MP + 2MP | 8MP ',
        descripcion:"1 año de garantía del fabricante para el teléfono y 6 meses de garantía en la caja"
    },
    {
        id:6,
        img:'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/4/h/e/-original-imagzjhwmsamexfk.jpeg?q=70',
        modelo:'vivo T2x ',
        marca:'Vivo',
        precio:2800,
        espacio:'6 GB RAM | 128 GB ROM',
        camara:'50MP + 2MP | 8MP Camara Frontal',
        bateria:'5000 mAh bateria',
        cantidad:1,
        estaAgreado:false,
        tipo:'Mobile',   
        esTendencia:false,
        descripcion:"1 año de garantía del fabricante para el teléfono y 6 meses de garantía en la caja"
    },
    {
        id:7,
        img:"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/g/b/x/-original-imagtt4h4ptmxgwn.jpeg?q=70",
        modelo:'Vivo T2 Pro',
        marca:'Vivo',
        precio:3500,
        espacio:'8 GB RAM | 128 GB ROM',
        camara:'108MP Camara Trasera',
        bateria:'5000 mAh bateria',
        cantidad:1,
        estaAgreado:false,
        tipo:'Mobile',   
        esTendencia:false,
        descripcion:"1 año de garantía del fabricante para el teléfono y 6 meses de garantía en la caja"
    },
    {
        id:8,
        img:"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/t/f/2/y27-v2249-vivo-original-imahfmkqf5mrugjq.jpeg?q=70",
        modelo:'Vivo Y27',
        marca:'Vivo',
        precio:3200,
        espacio:'8 GB RAM | 128 GB ROM',
        camara:'50MP + 2MP | 8MP Camara Frontal',
        bateria:'5000 mAh bateria',
        cantidad:1,
        estaAgreado:false,
        tipo:'Mobile',   
        esTendencia:false,
        descripcion:"1 año de garantía del fabricante para el teléfono y 6 meses de garantía en la caja"
    },
    {
        id:9,
        img:'https://m.media-amazon.com/images/I/61SSVxTSs3L._SX679_.jpg',
        modelo:'ColorFit Pulse',
        marca:'Fire-Bolt',
        precio:1400,
        color:'black',
        cantidad:1,
        estaAgreado:false,
        tipo:'Watch',   
        esTendencia:true,
        descripcion:"1 año de garantía del fabricante para el teléfono y 6 meses de garantía en la caja"
    },
    {
        id:10,
        img:'https://m.media-amazon.com/images/I/61Bdfmo2s0L._SX679_.jpg',
        modelo:'Lumos',
        marca:'Fire-Bolt',
        precio:1200,
        color:'	Steel Black',
        cantidad:1,
        estaAgreado:false,
        tipo:'Watch',   
        esTendencia:false,
        descripcion:"1 año de garantía del fabricante para el teléfono y 6 meses de garantía en la caja"
    },
]


export default productList;